apply plugin: "java"
apply plugin: "application"

group = "agency.highlysuspect"
version = "2.0"

java.toolchain.languageVersion = JavaLanguageVersion.of(8)
compileJava {
    sourceCompatibility = "8"
    targetCompatibility = "8"
}

repositories {
    mavenCentral()
}

dependencies {
    compileOnly "org.jetbrains:annotations:24.1.0"
    
    implementation "org.ow2.asm:asm:9.7"
    implementation "net.sf.jopt-simple:jopt-simple:6.0-alpha-3" //use this for args probably
    
    testImplementation platform("org.junit:junit-bom:5.9.1")
    testImplementation "org.junit.jupiter:junit-jupiter"
}

test {
    useJUnitPlatform()
}

application {
    mainClass = "agency.highlysuspect.jargrep.Cli"
}

tasks.register('fat', Jar) {
    group "build"
    
    manifest {
        attributes "Main-Class": project.application.mainClass
        attributes "Implementation-Version": project.version
    }
    archiveClassifier = "all"
    from {
        configurations.runtimeClasspath.collect {it.isDirectory() ? it : zipTree(it)}
    }
    with jar
}

//What
tasks.named("run").configure {
    it.dependsOn(tasks.named("build"))
    it.workingDir = file("./random-test-data")
}